# Generated by Django 6.0.3 on 2026-03-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome da Empresa')),
                ('razao_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo do Sistema')),
                ('cor_primaria', models.CharField(default='#FFD700', max_length=7, verbose_name='Cor Primária (Hex)')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Suporte')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
                'verbose_name_plural': 'Configurações da Empresa',
            },
        ),
    ]
