# Generated by Django 6.0.3 on 2026-03-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Automação')),
                ('tipo', models.CharField(choices=[('script', 'Script Python'), ('docker', 'Container Docker'), ('api', 'Integração API')], default='script', max_length=20)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('executando', 'Executando'), ('pendente', 'Pendente')], default='pendente', max_length=20)),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição técnica')),
            ],
            options={
                'verbose_name': 'Automação',
                'verbose_name_plural': 'Automações',
            },
        ),
    ]
