# Generated by Django 6.0.3 on 2026-03-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='automacao',
            name='tipo',
        ),
        migrations.AddField(
            model_name='automacao',
            name='planilha',
            field=models.FileField(blank=True, null=True, upload_to='automacoes/planilhas/', verbose_name='Arquivo Excel'),
        ),
        migrations.AddField(
            model_name='automacao',
            name='slug_script',
            field=models.CharField(default='default', help_text='Nome da função no tasks.py', max_length=50, verbose_name='Código do Script'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('parado', 'Parado'), ('concluido', 'Concluído'), ('falha', 'Falha')], default='pendente', max_length=20, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='automacao',
            name='ultima_execucao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Atualização'),
        ),
    ]
